language: python
arch:
  - amd64
  - ppc64le
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"
# Disable unsuported version  pypy for ppc64le
jobs:
  exclude:
  - arch: ppc64le
    python: pypy3

install:
  - pip install .
script:
  - python -m unittest discover
