from typing import List, Tuple

def intranges_from_list(list_: List[int]) -> Tuple[int, ...]: ...
def _encode_range(start: int, end: int) -> int: ...
def _decode_range(r: int) -> Tuple[int, int]: ...
def intranges_contain(int_: int, ranges: Tuple[int, ...]) -> bool: ...
